### ISSUE TITLE
How can run this plugin as xcj.bat(xcj.sh) instead of maven plugin?

### ISSUE THREAD

**Issue by yerganat** [buschmais/jaxbfx#12]

**Comment by toisrael** [comment]
First download the plugins jar and add this to the classpath with `xjc.bat -classpath` and add the parameter `-Xgenerate-fx-properties`.

**Comment by yerganat** [comment]
Yes, i have done like you
but it is work for Java 10/11 but nor work for Java 9, i think javax.activator implementation not acceptable for Java 9
I want to create any java version tools)

**Comment by toisrael** [comment]
I have created an issue for Java 9+ support. You can track this at #13 - If you’ve made it work already, a pull request would be great.

**Comment by toisrael** [comment]
Further work will be done with #13
