### ISSUE TITLE
Problems with unmarshalled objects

### ISSUE THREAD

**Issue by hphalle** [buschmais/jaxbfx#5]
It might be that I simply do not see the missing trick, but when I try to read an XML file using the jaxb unmarshaller and the classes generated by this plugin the objects read are almost unusable. This is because the unmarshaller uses direct access to the data fields by default, bypassing the setter methods. So after reading the data into a string property the String value contains this data, while the getString returns null becasue the StringProxy hasn't been set. Even worse, the type of a list element is constructed as ArrayList<T> by the unmarshaller, the getter tries to cast this to SimpleListProperty<T>, which results in an exception.

BTW: I tried to use the -Xpropertyaccessors xjc option as well, but that leads to problems during unmarshalling. This seems to be a unmarshaller issue.

**Comment by hphalle** [comment]
As I didn't find another solution I modified your solution to support unmarshalling. You can find it in the fork https://github.com/hphalle/jaxbfx.git. The change uses a lazy creation of the property objects. I didn't do a complete test, but it works for my application. Feel free to integrate the change into your repository.

**Comment by toisrael** [comment]
Thanks for using jaxbfx. Can you please provide some details about the JAXB2 implementation you are using?

**Comment by toisrael** [comment]
Thank you for contributing to jaxbfx! Including your changes I had to change the type for primitive wrappers to ObjectProperty (which I should have done from scratch...). Please pull these changes to make sure that it works for you. We'll schedule this bugfix release for a maven central deployment within the next few days to provide convenient build integration.

**Comment by hphalle** [comment]
As I couldn't spend time on this I tried your changes only now. The new version works fine for me.
