### ISSUE TITLE
Problem marshalling lists and values set via properties

### ISSUE THREAD

**Issue by hphalle** [buschmais/jaxbfx#8]
When marshalling XML beans not all changes made to the XML bean are written to the marshalled object:
- Objects appended to lists are missing completely
- Values written using the property objects are not present.

The reason is that the marshaller like the unmarshaller uses direct access to the fields bypassing the getter methods. These fields are not updated in the cases described above.

I implemented test methods and an incomplete solution which can be taken from https://github.com/hphalle/jaxbfx.git. The solution works if lambda expressions can be generated, which is fine for me as my project uses Java8. I tried to allow generation of Java7 as well, but this needs changes, because DoubleProperty etc. expect a ChangeListener<Number>.

**Comment by hphalle** [comment]
I had some time left and added a hack to support Java7 as well. You'll find it in my clone repository.

**Comment by janacht** [comment]
Hi,

I've encountered the same problem and my solution was to change the instantiation of the list properties from FXCollections.observableArrayList(list) to FXCollections.observableList(list) (FXBeanPropertyXJCPlugin.java:222). observableList is backed on the submitted list and uses it internally, whereas observableArrayList creates a new ArrayList with the elements that are in the list at instantiation.

**Comment by toisrael** [comment]
Thank's @hphalle for contributing to the issue. I slightly reworked your changes to make sure, the target platform of the plugin starts with Java 7.
